---
title: "Homework 1"
author: "Dillon, Futing, Ian"
date: "2/14/2022"
output: html_document
---
```{r}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
library(tidyverse)
library(rio)
library(here)
library(ungeviz)
library(janitor)
library(ggtext) 
library(gghighlight)
library(ggrepel)
library(ggforce)

transit_cost <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-05/transit_cost.csv')

# install.packages("tidytuesdayR")
country_codes <- countrycode::codelist %>% 
  select(country_name = country.name.en, country = ecb) %>% 
  na.omit()
transit_cost <- tidytuesdayR::tt_load(2021, week = 2) 
transit_df <- transit_cost[[1]] %>% 
  mutate(real_cost = as.numeric(real_cost))
transit <- left_join(transit_df, country_codes, by = "country")
crime <- import(here("crime.csv"))%>% clean_names()

```

Part 1
```{r, fig.width= 6.5, fig.height=10}
transit_sum <- transit %>% 
  group_by(country_name) %>% 
  summarize(n = n(), 
            mean_cost = mean(real_cost, na.rm = TRUE), 
            se_cost = sd(real_cost, na.rm = TRUE) / sqrt(n()), 
            lower = mean_cost + qnorm(0.025) * se_cost,
            upper = mean_cost + qnorm(0.975) * se_cost) %>% 
  filter(n>=3 & !is.na(country_name)) 
  
transit_sum %>% 
ggplot(., aes(mean_cost, reorder(country_name, mean_cost))) +
  geom_errorbarh(
    aes(xmin = ifelse(
        lower<0, 0, 
        lower),
        xmax = upper, 
        height = 0), 
    alpha = .8) +
  geom_point(colour = "cornflowerblue")+
  scale_x_continuous(labels = scales::comma)+
  theme_minimal()+
  labs(title = "Cost to build transit systems vary across countries", 
       x = "Real Cost (In millions of dollars)", 
       caption = "Data provided through #tidytuesday by the Transit Costs Project", 
       y = "Country")+
  theme(
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title.position = "plot", 
    #plot.caption.position = "center"
    plot.caption = element_text(hjust = 0.5))
```

# Part 2
```{r, fig.width= 6.5, fig.height=10}
transit_sum %>% 
ggplot(., aes(mean_cost, reorder(country_name, mean_cost))) +
   stat_confidence_density(
     aes( moe = se_cost), 
     fill = "darkslategray4", 
     height = 0.4   ) +
  geom_point(colour = "cornflowerblue")+
  scale_x_continuous(labels = scales::comma)+
  theme_minimal()+
  labs(title = "Cost to build transit systems vary across countries", 
       x = "Real Cost (In millions of dollars)", 
       caption = "Data provided through #tidytuesday by the Transit Costs Project", 
       y = "Country")+
  theme(
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title.position = "plot", 
    #plot.caption.position = "center"
    plot.caption = element_text(hjust = 0.5), 
    text =element_text(family = "Charter") )  

```




# Part 3
```{r}
by_city <- transit %>% 
  group_by(city, country_name) %>%
  summarize(length_mean= mean(length, na.rm = TRUE),
            real_cost_mean = mean(real_cost, na.rm = TRUE),
            num_trans = n())

ggplot(by_city, aes(length_mean, real_cost_mean)) +
  geom_point(aes(size = num_trans), color = "#AC05B0") +
  scale_size_binned("Number of transit systems", breaks = c(5, 10, 20)) +
  gghighlight(country_name == "India") +
  geom_text_repel(aes(label = city),
                  min.segment.length = 0,
                  box.padding = 0.18) +
  scale_x_log10(limits=c(NA,200)) +
  scale_y_log10(labels = scales::dollar) +
  theme_minimal(base_size = 14) +
  labs(title = "Longer transit systems tend to cost more",
       subtitle = "<span style='color: #AC05B0;'>India</span> has among the most transit systems in the world",
         caption = "Note the axes are on the log scale",
         x = "Average length",
         y = "Average cost") +
  theme(plot.subtitle = element_markdown(),
        plot.title.position = "plot",
        axis.title.y = element_text(size = 13),
        axis.title.x = element_text(size = 13),
        legend.position = "bottom"
        ) 
```

# Part 4
```{r}
by_city %>%
  drop_na() %>%
ggplot(aes(length_mean, real_cost_mean)) +
  geom_point(aes(size = num_trans), colour="#6099DF") +
  geom_mark_ellipse(aes(group = country_name, label = country_name), color = "#E799BF",
                    data = filter(drop_na(by_city), country_name == "United States"),
                    label.colour = "#6099DF", 
                    con.colour = "#E799BF") + 
  scale_size_binned("Number of transit systems", breaks = c(5, 10, 20)) +
  gghighlight(country_name == "United States") +
  geom_text_repel(aes(label = city),
                  min.segment.length = 0,
                  box.padding = 0.18) +
  scale_x_log10(limits=c(NA,200)) +
  scale_y_log10(labels = scales::dollar) +
  theme_minimal(base_size = 14) +
  labs(title = "Longer transit systems tend to cost more",
         caption = "Note the axes are on the log scale",
         x = "Average length",
         y = "Average cost") +
  theme(plot.title.position = "plot",
        axis.title.y = element_text(size = 13),
        axis.title.x = element_text(size = 13),
        legend.position = "bottom"
        ) 
```



# Part 5
```{r}
model_data <- crime %>% 
  mutate(neighborhood_id = relevel(factor(neighborhood_id), ref = "barnum"))

m <- glm(is_crime ~ neighborhood_id, 
         data = model_data,
         family = "binomial")

tidied <- broom::tidy(m)

ppoints(20)

barnumwest <- tidied %>% 
  filter(term == "neighborhood_idbarnum-west")

qnorm(ppoints(20), 
      mean = barnumwest$estimate,
      sd = barnumwest$std.error)

discretized2 <- data.frame(
  x = qnorm(ppoints(20), mean = barnumwest$estimate, sd = barnumwest$std.error)) 
discretized2 <- discretized2 %>% mutate(winner = ifelse(x <= 0, "#b1daf4", "#f8f1a9"))

ggplot(discretized2, aes(x)) +
  geom_dotplot(aes(fill = winner), binwidth = 0.022) +
  geom_vline(xintercept = 0, 
             color = "red4", 
             linetype = 1, 
             size = 3) +
  scale_fill_identity(guide = "none") +
  scale_y_continuous(name = "", 
                     breaks = NULL)+
  scale_x_continuous(name = "", 
                     breaks = seq(-.1, .1, .05)) +
  labs(x = "Difference in log odds of a crime being committed",
       y = "",
       caption = "Each ball represents 5% probability",
       title = "Probability of differential crime rates between neighborhoods",
       subtitle = "Barnum West vs Barnum")+
  theme_minimal()
```


