---
title: "Lab 1"
author: "Ian Shryock"
date: "1/10/2022"
output: html_document
---


```{r setup}
library(here)
library(rio)
library(ggplot2)
library(stringr)
library(tidyverse)
library(tidytext)
```

```{r loadData}
tweetsData <- readRDS(here("rstats_tweets.rds"))
```

```{r part1}
ggplot(tweetsData, aes(x = display_text_width)) +
  geom_histogram(fill = "#56B4E9",
                 color = "white",
                 alpha = 0.9,
                 bins = 10)

ggplot(tweetsData, aes(x = display_text_width)) +
  geom_histogram(fill = "#56B4E9",
                 color = "white",
                 alpha = 0.9,
                 bins = 20)

ggplot(tweetsData, aes(x = display_text_width)) +
  geom_histogram(fill = "#56B4E9",
                 color = "white",
                 alpha = 0.9,
                 bins = 50)

ggplot(tweetsData, aes(x = display_text_width)) +
  geom_histogram(fill = "#56B4E9",
                 color = "white",
                 alpha = 0.9,
                 bins = 100)

#I don't know what we would use these insights for. The 10 bin shows the central tendencies. 20 bins makes the general pattern clear. 50 bins shows the modal response spike. 100 is incrementally more granular than 50. Overall, my inclination would be for 20 or 50, leaning slightly to 50.
```

```{r part2}
table <- table(grepl("text", tweetsData$text))

# The proportion is 4597 of 429513
```

```{r part3}
#unnest words
tidy_tweets <- tweetsData %>% 
  unnest_tokens(word, text)

#bad count
tidy_tweets %>% 
  count(word, sort = TRUE)

#get rid of common but irrelevant words
tidy_tweets_sub <-tidy_tweets[!(tidy_tweets$word %in% c("t.co", "https", "http", "rt", "rstats")), ]

# get rid of more irrelevant words and take 15 most common
top_15 <- tidy_tweets_sub %>% 
  anti_join(stop_words) %>% 
  count(word, sort = TRUE) %>% 
  head(., 15)

#three puke version
top_15 %>% 
  ggplot(.,aes(word, n))+
  geom_col()

#two puke version
top_15 %>% 
  ggplot(.,aes(word, n))+
  geom_col()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 10))

#one puke version
top_15 %>% 
  ggplot(.,aes(word, n))+
  geom_col()+
  coord_flip()

#sneaky face version
top_15 %>% 
  ggplot(.,aes(fct_reorder(word, n), n))+
  geom_col()+
  coord_flip() +
  labs(x = "Word")

```

```{r part4}
# style plot
top_15 %>% 
  ggplot(.,aes(fct_reorder(word, n), n))+
  geom_col(fill = "cornflowerblue", alpha = .9)+
  coord_flip() +
  labs(
    title = "Word frequencies in posts",
    subtitle = "Top 15 words displayed",
    caption = "Data from Mike Kearny, distributed via #tidytuesday",
    x = "Word", 
    y="Count"
  ) +
  theme_minimal(base_size = 14) +
  theme(plot.title.position = "plot",
        panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_line(color = "#A9A9A9", size = .6),
        panel.grid.minor.x = element_blank())
```

