---
title: "Lab 2"
author: "Ian Shryock"
date: "1/24/2022"
output: html_document
---
```{r}

library(fivethirtyeight)
library(fivethirtyeightdata)
library(viridis)
library(hrbrthemes)
library(tidyverse)

google_trends <- google_trends
tv_state <- tv_states
comic_characters <- comic_characters


```

# With Google
```{r}

colnames(google_trends) <- gsub("hurricane_|_us", "", colnames(google_trends))

google_trends_long <- google_trends %>% 
  pivot_longer(., cols = -c("date"), names_to = "hurricane", values_to = "values" )

google_trends_long$hurricane <- as.factor(google_trends_long$hurricane)


google_trends_long %>% 
  ggplot(., aes(x = date,  group = hurricane, y = values, color = hurricane )) +
  geom_point(alpha=.45) +
    theme_ipsum()


google_trends_long %>% 
  ggplot(., aes(x = date,  group = hurricane, fill)) +
  geom_density(adjust=1.5, alpha=.2) 



google_trends_long %>% 
  ggplot(., aes(x = date,  group = hurricane, fill = hurricane )) +
    geom_ribbon(aes(ymin = values - 1.96*sd(values) , 
                    ymax = values + 1.96*sd(values)), fill = "grey70") +
  geom_line(aes(y = values)) +
    theme_ipsum()


```

# Comics
```{r}

comic_characters <- comic_characters %>% 
  mutate(sex = gsub(" Characters", "", sex))
comic_characters$sex <- as.factor(comic_characters$sex) 

comic_characters %>% 
  ggplot(aes(sex))+
  geom_histogram()

sex_sums <- comic_characters %>% 
  summarize(sex_sum = sum(count(sex)))

ggplot(comic_characters, aes(x="", y=sex, fill=sex)) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0)


```

